name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        timeout-minutes: 1
        run: |
          COMMAND="./scripts/deploy.sh"
          COMMAND="TRACING=file:./update.trace $COMMAND"
          exec $COMMAND
